### ISSUE TITLE
Node.js不能最新版吗？

### ISSUE THREAD

**Issue by SuiranQaQ** [JaguarJack/catch-admin-vue#28]
运行起来报错
10% building 2/2 modules 0 activeError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\hot\dev-server.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\Suiran\Desktop\Demo\catch-admin-vue\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0

**Comment by SuiranQaQ** [comment]
好的，用了node14版本可以运行了
